version: '3.8'

services:
  localhost:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: pdf_database
    ports:
      - "3306:3306"

  php:
    image: php:apache
    volumes:
      - ./path/to/your/php/files:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - db
