version: '3.1'

services:
  app:
    image: php:7.4-apache
    container_name: php-app
    volumes:
      - ./src:/var/www/html
    networks:
      - app-network

  db:
    image: mysql:latest
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: pdf_database
      MYSQL_USER: root
      MYSQL_PASSWORD: root_password
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
